### ISSUE TITLE
Missing tech node

### ISSUE THREAD

**Issue by Tonas1997** [Orthethac/HideEmptyTechTreeNodes#13]
There's a tech tree node that's not making it into the pruned tech tree. Cache shows the "cryonics" node is properly configured and has parts depending on it, but it's missing from HETTN.TechTree.

![screenshot2](https://user-images.githubusercontent.com/43859708/126694368-d4831f81-d949-45ed-8659-2b1495ab0ad2.png)

Zip file contains the KSP log, the HETTN tree and the ModuleManager cache.
[Files.zip](https://github.com/Orthethac/HideEmptyTechTreeNodes/files/6864682/Files.zip)

**Comment by Orthethac** [comment]
Sorry for the delay. I will take a look.

**Comment by Tonas1997** [comment]
Closing this issue as further inspection revealed the problem to be caused by another mod
