### ISSUE TITLE
Custom TechTree tied to Module Manager unnecessarily.

### ISSUE THREAD

**Issue by Lisias** [Orthethac/HideEmptyTechTreeNodes#2]
The present implementation of HideEmptyTechTreeNodes assumes that Module Manager is the only Custom TechTree manager available.

Ideally, this plugin should adapt itself to whatever TechTree  manager is running at the moment.

More information are available here:
https://github.com/net-lisias-ksp/ModuleManager/blob/master/Source/ModuleManager/CustomConfigsManager.cs

**Comment by Orthethac** [comment]
Could not reproduce. See Pull Request.
