### ISSUE TITLE
Hide Empty Tech Tree Nodes breaks TETRIX Tech tree

### ISSUE THREAD

**Issue by Monniasza** [Orthethac/HideEmptyTechTreeNodes#9]
@theJesuit

HETTN conflicts TETRIX Tech Tree by removing some nodes from the tech tree. The result is a tree with broken pathways, nodes that lead nowhere, and missing nodes. And TETRIX nodes do not even appear. HETTN also ignores settings in this case and removes the required nodes.

Here's what tech tree should look like:![Go (here)[https://forum.kerbalspaceprogram.com/index.php?/topic/174731-19x-tetrix-techtree-25-and-simplex-techtree-116/page/11/&tab=comments#comment-3809380]](https://i.imgur.com/2HfCPvu.png)
An here's how it looks:![](http://u.cubeupload.com/Monniasza/howitisHETTN.png)

SSTO Project, KSP Interstellar Extended, Impossible Innovations, and Bargain Rocket Parts Recycled do not cause this issue (but they still add tch nodes).

**Comment by theJesuit** [comment]
KSPIE should not be adding nodes as TETRIX suppresses KSPIE doing so.

SSTO Project, Impossible Innovations and Bargain Rocket Parts Recycled are not listed as supported by TETRIX Tech Tree and without these, Hide Empty TechTreee Nodes doesn't have an issue with Tetrix Tree.  More investigation is needed.

**Comment by theJesuit** [comment]
From the fourm page:

SpaceY was supported in the most recent versions of TETRIX and the tree does the same - suppressing the creation of nodes.

If CKAN installs CTT with KSPIE then there isn't much I can do about that, that is the responsibility of @FreeThinkerand the CKAN team.

FreeThinker kindly did give me assistance in developing TETRIX with what nodes were required specifically for KSPIE and the mods it includes and another issue could be that TETRIX itself adds a couple of nodes if KSPIE is installed (a 2*node 10th tier for the warp components).  So if KSPIE is being added and removed (or any other mods that are adding in nodes for that matter) I have found that MM struggles to maintain techtree integrity inside a save game you are using a specific save game for testing.  It seems a little random, but if you start fresh each time there shouldn't be a problem.

In testing I always start a 'new' default save game to avoid any issues.

**Comment by Monniasza** [comment]
@theJesuit
But here a conflict between HETTN and TETRIX is described.

**Comment by Orthethac** [comment]
@Monniasza @theJesuit Sorry for the extremely late reply. I've been away, but I'm back.

Is this still an issue? TETRIX seems to use ModuleManager, which my mod is intended to work with, so I don't immediately see why there would be an issue. But I'd be happy to investigate. Could you please provide your log file and a list of installed mods?

**Comment by theJesuit** [comment]
The issue i believe is when you add or remove HETTN within a save.  That rather disfigures things withing the MM config cache for a save.

**Comment by Orthethac** [comment]
Hmm I've deleted HETTN during a save many times as part of testing and haven't seen this. Maybe I missed something in my tests. HETTN regenerates a brand new TechTree file directly from the ModuleManager.TechTree file each time the user loads their game. If MM changes, HETTN should change as well. I don't think HETTN is cached by MM. Thoughts?

Two major problems I encounter are
(1) HETTN (and ModuleManager) don't like it when you have more than .cfg file with a TechTree node in it (HETTN uses a .TechTree extension, not .cfg, so it isn't collected in the GameDatabase on startup). This is usually what causes issues. Editing the stock TechTree node with MM works best.
(2) Unlocking parts, and then adding mods that move the already unlocked parts causes some issues with part unlocks, but I've never seen break a tree.

**Comment by Orthethac** [comment]
Current pre-release for HETTN v1.3.1 might fix this exception error.

There was an issue where I was trying to use a Parent ID to look up a research node, but if the node doesn't actually exist then there was an exception that I did not handle.

**Comment by Orthethac** [comment]
Fixed in v1.3.1.
